package be.perrybmwghosttje.droidcraft.client.renderer.models;

import cpw.mods.fml.relauncher.Side;
import cpw.mods.fml.relauncher.SideOnly;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

@SideOnly(Side.CLIENT)
public class ModelEngine extends ModelBase {
    //fields
    ModelRenderer Ground_Platform;
    ModelRenderer On_Off_Panel;
    ModelRenderer Generator_Base_Part;
    ModelRenderer Front_Base_Part;
    ModelRenderer Back_Base_Part;
    ModelRenderer Left_From_Behind_Vertical_Support;
    ModelRenderer Right_From_Behind_Vertical_Support;
    ModelRenderer Up_From_Behind_Horizontal_Support;
    ModelRenderer Right_Side_Up_Support;
    ModelRenderer Left_Side_Up_Support;
    ModelRenderer Left_From_Behind_Support_Leg;
    ModelRenderer Left_Front_Support_Leg;
    ModelRenderer Right_From_Behind_Support_Leg;
    ModelRenderer Right_Front_Support_Leg;
    ModelRenderer Back_Base_Part_2;
    ModelRenderer Front_Right_Vertical_Support;
    ModelRenderer Front_Left_Vertical_Support;
    ModelRenderer Cilinder_Left_Back;
    ModelRenderer Cilinder_Left_Middle;
    ModelRenderer Cilinder_Left_Front;
    ModelRenderer Cilinder_Right_Back;
    ModelRenderer Cilinder_Right_Middle;
    ModelRenderer Cilinder_Right_Front;

    public ModelEngine() {
        textureWidth = 128;
        textureHeight = 64;

        Ground_Platform = new ModelRenderer(this, 0, 0);
        Ground_Platform.addBox(0F, 0F, 0F, 16, 1, 16);
        Ground_Platform.setRotationPoint(-8F, 23F, -8F);
        Ground_Platform.setTextureSize(128, 64);
        Ground_Platform.mirror = true;
        setRotation(Ground_Platform, 0F, 0F, 0F);
        On_Off_Panel = new ModelRenderer(this, 0, 17);
        On_Off_Panel.addBox(0F, 0F, 0F, 1, 3, 16);
        On_Off_Panel.setRotationPoint(-8F, 8F, -8F);
        On_Off_Panel.setTextureSize(128, 64);
        On_Off_Panel.mirror = true;
        setRotation(On_Off_Panel, 0F, 0F, 0F);
        Generator_Base_Part = new ModelRenderer(this, 64, 0);
        Generator_Base_Part.addBox(-7F, 11F, -5F, 10, 10, 10);
        Generator_Base_Part.setRotationPoint(2F, 0F, 0F);
        Generator_Base_Part.setTextureSize(128, 64);
        Generator_Base_Part.mirror = true;
        setRotation(Generator_Base_Part, 0F, 0F, 0F);
        Front_Base_Part = new ModelRenderer(this, 35, 18);
        Front_Base_Part.addBox(0F, 0F, 0F, 2, 6, 6);
        Front_Base_Part.setRotationPoint(-7F, 13F, -3F);
        Front_Base_Part.setTextureSize(128, 64);
        Front_Base_Part.mirror = true;
        setRotation(Front_Base_Part, 0F, 0F, 0F);
        Back_Base_Part = new ModelRenderer(this, 35, 18);
        Back_Base_Part.addBox(0F, 0F, 0F, 2, 6, 6);
        Back_Base_Part.setRotationPoint(5F, 13F, -3F);
        Back_Base_Part.setTextureSize(128, 64);
        Back_Base_Part.mirror = true;
        setRotation(Back_Base_Part, 0F, 0F, 0F);
        Left_From_Behind_Vertical_Support = new ModelRenderer(this, 53, 19);
        Left_From_Behind_Vertical_Support.addBox(0F, 0F, 0F, 1, 15, 1);
        Left_From_Behind_Vertical_Support.setRotationPoint(7F, 8F, 7F);
        Left_From_Behind_Vertical_Support.setTextureSize(128, 64);
        Left_From_Behind_Vertical_Support.mirror = true;
        setRotation(Left_From_Behind_Vertical_Support, 0F, 0F, 0F);
        Right_From_Behind_Vertical_Support = new ModelRenderer(this, 58, 19);
        Right_From_Behind_Vertical_Support.addBox(0F, 0F, 0F, 1, 15, 1);
        Right_From_Behind_Vertical_Support.setRotationPoint(7F, 8F, -8F);
        Right_From_Behind_Vertical_Support.setTextureSize(128, 64);
        Right_From_Behind_Vertical_Support.mirror = true;
        setRotation(Right_From_Behind_Vertical_Support, 0F, 0F, 0F);
        Up_From_Behind_Horizontal_Support = new ModelRenderer(this, 0, 49);
        Up_From_Behind_Horizontal_Support.addBox(0F, 0F, -7F, 1, 1, 14);
        Up_From_Behind_Horizontal_Support.setRotationPoint(7F, 8F, 0F);
        Up_From_Behind_Horizontal_Support.setTextureSize(128, 64);
        Up_From_Behind_Horizontal_Support.mirror = true;
        setRotation(Up_From_Behind_Horizontal_Support, 0F, 0F, 0F);
        Right_Side_Up_Support = new ModelRenderer(this, 32, 49);
        Right_Side_Up_Support.addBox(0F, 0F, 0F, 14, 1, 1);
        Right_Side_Up_Support.setRotationPoint(-7F, 8F, -8F);
        Right_Side_Up_Support.setTextureSize(128, 64);
        Right_Side_Up_Support.mirror = true;
        setRotation(Right_Side_Up_Support, 0F, 0F, 0F);
        Left_Side_Up_Support = new ModelRenderer(this, 32, 52);
        Left_Side_Up_Support.addBox(0F, 0F, 0F, 14, 1, 1);
        Left_Side_Up_Support.setRotationPoint(-7F, 8F, 7F);
        Left_Side_Up_Support.setTextureSize(128, 64);
        Left_Side_Up_Support.mirror = true;
        setRotation(Left_Side_Up_Support, 0F, 0F, 0F);
        Left_From_Behind_Support_Leg = new ModelRenderer(this, 32, 55);
        Left_From_Behind_Support_Leg.addBox(0F, 0F, 0F, 1, 2, 1);
        Left_From_Behind_Support_Leg.setRotationPoint(3F, 21F, 3F);
        Left_From_Behind_Support_Leg.setTextureSize(128, 64);
        Left_From_Behind_Support_Leg.mirror = true;
        setRotation(Left_From_Behind_Support_Leg, 0F, 0F, 0F);
        Left_Front_Support_Leg = new ModelRenderer(this, 37, 55);
        Left_Front_Support_Leg.addBox(0F, 0F, 0F, 1, 2, 1);
        Left_Front_Support_Leg.setRotationPoint(-4F, 21F, 3F);
        Left_Front_Support_Leg.setTextureSize(128, 64);
        Left_Front_Support_Leg.mirror = true;
        setRotation(Left_Front_Support_Leg, 0F, 0F, 0F);
        Right_From_Behind_Support_Leg = new ModelRenderer(this, 37, 59);
        Right_From_Behind_Support_Leg.addBox(0F, 0F, 0F, 1, 2, 1);
        Right_From_Behind_Support_Leg.setRotationPoint(3F, 21F, -4F);
        Right_From_Behind_Support_Leg.setTextureSize(128, 64);
        Right_From_Behind_Support_Leg.mirror = true;
        setRotation(Right_From_Behind_Support_Leg, 0F, 0F, 0F);
        Right_Front_Support_Leg = new ModelRenderer(this, 32, 59);
        Right_Front_Support_Leg.addBox(0F, 0F, 0F, 1, 2, 1);
        Right_Front_Support_Leg.setRotationPoint(-4F, 21F, -4F);
        Right_Front_Support_Leg.setTextureSize(128, 64);
        Right_Front_Support_Leg.mirror = true;
        setRotation(Right_Front_Support_Leg, 0F, 0F, 0F);
        Back_Base_Part_2 = new ModelRenderer(this, 39, 38);
        Back_Base_Part_2.addBox(0F, 0F, 0F, 1, 4, 4);
        Back_Base_Part_2.setRotationPoint(7F, 14F, -2F);
        Back_Base_Part_2.setTextureSize(128, 64);
        Back_Base_Part_2.mirror = true;
        setRotation(Back_Base_Part_2, 0F, 0F, 0F);
        Front_Right_Vertical_Support = new ModelRenderer(this, 66, 36);
        Front_Right_Vertical_Support.addBox(0F, 0F, 0F, 1, 12, 1);
        Front_Right_Vertical_Support.setRotationPoint(-8F, 11F, -8F);
        Front_Right_Vertical_Support.setTextureSize(128, 64);
        Front_Right_Vertical_Support.mirror = true;
        setRotation(Front_Right_Vertical_Support, 0F, 0F, 0F);
        Front_Left_Vertical_Support = new ModelRenderer(this, 60, 36);
        Front_Left_Vertical_Support.addBox(0F, 0F, 0F, 1, 12, 1);
        Front_Left_Vertical_Support.setRotationPoint(-8F, 10.93333F, 7F);
        Front_Left_Vertical_Support.setTextureSize(128, 64);
        Front_Left_Vertical_Support.mirror = true;
        setRotation(Front_Left_Vertical_Support, 0F, 0F, 0F);
        Cilinder_Left_Back = new ModelRenderer(this, 76, 24);
        Cilinder_Left_Back.addBox(0F, 0F, 0F, 2, 3, 2);
        Cilinder_Left_Back.setRotationPoint(2F, 9F, 2F);
        Cilinder_Left_Back.setTextureSize(128, 64);
        Cilinder_Left_Back.mirror = true;
        setRotation(Cilinder_Left_Back, -0.3949431F, 0F, 0F);
        Cilinder_Left_Middle = new ModelRenderer(this, 76, 24);
        Cilinder_Left_Middle.addBox(0F, 0F, 0F, 2, 3, 2);
        Cilinder_Left_Middle.setRotationPoint(-1F, 9F, 2F);
        Cilinder_Left_Middle.setTextureSize(128, 64);
        Cilinder_Left_Middle.mirror = true;
        setRotation(Cilinder_Left_Middle, -0.3949431F, 0F, 0F);
        Cilinder_Left_Front = new ModelRenderer(this, 76, 24);
        Cilinder_Left_Front.addBox(0F, 0F, 0F, 2, 3, 2);
        Cilinder_Left_Front.setRotationPoint(-4F, 9F, 2F);
        Cilinder_Left_Front.setTextureSize(128, 64);
        Cilinder_Left_Front.mirror = true;
        setRotation(Cilinder_Left_Front, -0.3949431F, 0F, 0F);
        Cilinder_Right_Back = new ModelRenderer(this, 76, 24);
        Cilinder_Right_Back.addBox(0F, 0F, 0F, 2, 3, 2);
        Cilinder_Right_Back.setRotationPoint(2F, 9.7F, -4F);
        Cilinder_Right_Back.setTextureSize(128, 64);
        Cilinder_Right_Back.mirror = true;
        setRotation(Cilinder_Right_Back, 0.3949506F, 0F, 0F);
        Cilinder_Right_Middle = new ModelRenderer(this, 76, 24);
        Cilinder_Right_Middle.addBox(0F, 0F, 0F, 2, 3, 2);
        Cilinder_Right_Middle.setRotationPoint(-1F, 9.7F, -4F);
        Cilinder_Right_Middle.setTextureSize(128, 64);
        Cilinder_Right_Middle.mirror = true;
        setRotation(Cilinder_Right_Middle, 0.3949506F, 0F, 0F);
        Cilinder_Right_Front = new ModelRenderer(this, 76, 24);
        Cilinder_Right_Front.addBox(0F, 0F, 0F, 2, 3, 2);
        Cilinder_Right_Front.setRotationPoint(-4F, 9.7F, -4F);
        Cilinder_Right_Front.setTextureSize(128, 64);
        Cilinder_Right_Front.mirror = true;
        setRotation(Cilinder_Right_Front, 0.3949506F, 0F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        Ground_Platform.render(f5);
        On_Off_Panel.render(f5);
        Generator_Base_Part.render(f5);
        Front_Base_Part.render(f5);
        Back_Base_Part.render(f5);
        Left_From_Behind_Vertical_Support.render(f5);
        Right_From_Behind_Vertical_Support.render(f5);
        Up_From_Behind_Horizontal_Support.render(f5);
        Right_Side_Up_Support.render(f5);
        Left_Side_Up_Support.render(f5);
        Left_From_Behind_Support_Leg.render(f5);
        Left_Front_Support_Leg.render(f5);
        Right_From_Behind_Support_Leg.render(f5);
        Right_Front_Support_Leg.render(f5);
        Back_Base_Part_2.render(f5);
        Front_Right_Vertical_Support.render(f5);
        Front_Left_Vertical_Support.render(f5);
        Cilinder_Left_Back.render(f5);
        Cilinder_Left_Middle.render(f5);
        Cilinder_Left_Front.render(f5);
        Cilinder_Right_Back.render(f5);
        Cilinder_Right_Middle.render(f5);
        Cilinder_Right_Front.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    }
}