// Date: 14/07/2015 11:32:30
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package be.perrybmwghosttje.examplemod.client.renderer.models;

import cpw.mods.fml.relauncher.Side;
import cpw.mods.fml.relauncher.SideOnly;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

@SideOnly(Side.CLIENT)
public class ModelEngine extends ModelBase
{
  //fields
  ModelRenderer Shape1;
  ModelRenderer Shape2;
  ModelRenderer Shape3;
  ModelRenderer Shape4;
  ModelRenderer Shape5;
  ModelRenderer Shape6;
  ModelRenderer Shape7;
  ModelRenderer Shape8;
  ModelRenderer Cilinder;

  public ModelEngine()
  {
    textureWidth = 128;
    textureHeight = 64;

    Shape1 = new ModelRenderer(this, 0, 0);
    Shape1.addBox(0F, 0F, 0F, 16, 1, 16);
    Shape1.setRotationPoint(-8F, 23F, -8F);
    Shape1.setTextureSize(128, 64);
    Shape1.mirror = true;
    setRotation(Shape1, 0F, 0F, 0F);
   /* Shape2 = new ModelRenderer(this, 0, 17);
    Shape2.addBox(0F, 0F, 0F, 1, 3, 16);
    Shape2.setRotationPoint(-8F, 8F, -8F);
    Shape2.setTextureSize(128, 64);
    Shape2.mirror = true;
    setRotation(Shape2, 0F, 0F, 0F);
    Shape3 = new ModelRenderer(this, 64, 0);
    Shape3.addBox(-7F, 11F, -5F, 10, 10, 10);
    Shape3.setRotationPoint(2F, 0F, 0F);
    Shape3.setTextureSize(128, 64);
    Shape3.mirror = true;
    setRotation(Shape3, 0F, 0F, 0F);
    Shape4 = new ModelRenderer(this, 35, 18);
    Shape4.addBox(0F, 0F, 0F, 2, 6, 6);
    Shape4.setRotationPoint(-7F, 13F, -3F);
    Shape4.setTextureSize(128, 64);
    Shape4.mirror = true;
    setRotation(Shape4, 0F, 0F, 0F);
    Shape4 = new ModelRenderer(this, 35, 18);
    Shape4.addBox(0F, 0F, 0F, 2, 6, 6);
    Shape4.setRotationPoint(5F, 13F, -3F);
    Shape4.setTextureSize(128, 64);
    Shape4.mirror = true;
    setRotation(Shape4, 0F, 0F, 0F);
    Shape5 = new ModelRenderer(this, 53, 19);
    Shape5.addBox(0F, 0F, 0F, 1, 15, 1);
    Shape5.setRotationPoint(7F, 8F, 7F);
    Shape5.setTextureSize(128, 64);
    Shape5.mirror = true;
    setRotation(Shape5, 0F, 0F, 0F);
    Shape5 = new ModelRenderer(this, 58, 19);
    Shape5.addBox(0F, 0F, 0F, 1, 15, 1);
    Shape5.setRotationPoint(7F, 8F, -8F);
    Shape5.setTextureSize(128, 64);
    Shape5.mirror = true;
    setRotation(Shape5, 0F, 0F, 0F);
    Shape2 = new ModelRenderer(this, 0, 49);
    Shape2.addBox(0F, 0F, -7F, 1, 1, 14);
    Shape2.setRotationPoint(7F, 8F, 0F);
    Shape2.setTextureSize(128, 64);
    Shape2.mirror = true;
    setRotation(Shape2, 0F, 0F, 0F);
    Shape2 = new ModelRenderer(this, 32, 49);
    Shape2.addBox(0F, 0F, 0F, 14, 1, 1);
    Shape2.setRotationPoint(-7F, 8F, -8F);
    Shape2.setTextureSize(128, 64);
    Shape2.mirror = true;
    setRotation(Shape2, 0F, 0F, 0F);
    Shape2 = new ModelRenderer(this, 32, 52);
    Shape2.addBox(0F, 0F, 0F, 14, 1, 1);
    Shape2.setRotationPoint(-7F, 8F, 7F);
    Shape2.setTextureSize(128, 64);
    Shape2.mirror = true;
    setRotation(Shape2, 0F, 0F, 0F);
    Shape6 = new ModelRenderer(this, 32, 55);
    Shape6.addBox(0F, 0F, 0F, 1, 2, 1);
    Shape6.setRotationPoint(3F, 21F, 3F);
    Shape6.setTextureSize(128, 64);
    Shape6.mirror = true;
    setRotation(Shape6, 0F, 0F, 0F);
    Shape6 = new ModelRenderer(this, 37, 55);
    Shape6.addBox(0F, 0F, 0F, 1, 2, 1);
    Shape6.setRotationPoint(-4F, 21F, 3F);
    Shape6.setTextureSize(128, 64);
    Shape6.mirror = true;
    setRotation(Shape6, 0F, 0F, 0F);
    Shape6 = new ModelRenderer(this, 37, 59);
    Shape6.addBox(0F, 0F, 0F, 1, 2, 1);
    Shape6.setRotationPoint(3F, 21F, -4F);
    Shape6.setTextureSize(128, 64);
    Shape6.mirror = true;
    setRotation(Shape6, 0F, 0F, 0F);
    Shape6 = new ModelRenderer(this, 32, 59);
    Shape6.addBox(0F, 0F, 0F, 1, 2, 1);
    Shape6.setRotationPoint(-4F, 21F, -4F);
    Shape6.setTextureSize(128, 64);
    Shape6.mirror = true;
    setRotation(Shape6, 0F, 0F, 0F);
    Shape7 = new ModelRenderer(this, 39, 38);
    Shape7.addBox(0F, 0F, 0F, 1, 4, 4);
    Shape7.setRotationPoint(7F, 14F, -2F);
    Shape7.setTextureSize(128, 64);
    Shape7.mirror = true;
    setRotation(Shape7, 0F, 0F, 0F);
    Shape8 = new ModelRenderer(this, 66, 36);
    Shape8.addBox(0F, 0F, 0F, 1, 12, 1);
    Shape8.setRotationPoint(-8F, 11F, -8F);
    Shape8.setTextureSize(128, 64);
    Shape8.mirror = true;
    setRotation(Shape8, 0F, 0F, 0F);
    Shape8 = new ModelRenderer(this, 60, 36);
    Shape8.addBox(0F, 0F, 0F, 1, 12, 1);
    Shape8.setRotationPoint(-8F, 10.93333F, 7F);
    Shape8.setTextureSize(128, 64);
    Shape8.mirror = true;
    setRotation(Shape8, 0F, 0F, 0F);
    Cilinder = new ModelRenderer(this, 76, 24);
    Cilinder.addBox(0F, 0F, 0F, 2, 3, 2);
    Cilinder.setRotationPoint(2F, 9F, 2F);
    Cilinder.setTextureSize(128, 64);
    Cilinder.mirror = true;
    setRotation(Cilinder, -0.3949431F, 0F, 0F);
    Cilinder = new ModelRenderer(this, 76, 24);
    Cilinder.addBox(0F, 0F, 0F, 2, 3, 2);
    Cilinder.setRotationPoint(-1F, 9F, 2F);
    Cilinder.setTextureSize(128, 64);
    Cilinder.mirror = true;
    setRotation(Cilinder, -0.3949431F, 0F, 0F);
    Cilinder = new ModelRenderer(this, 76, 24);
    Cilinder.addBox(0F, 0F, 0F, 2, 3, 2);
    Cilinder.setRotationPoint(-4F, 9F, 2F);
    Cilinder.setTextureSize(128, 64);
    Cilinder.mirror = true;
    setRotation(Cilinder, -0.3949431F, 0F, 0F);
    Cilinder = new ModelRenderer(this, 76, 24);
    Cilinder.addBox(0F, 0F, 0F, 2, 3, 2);
    Cilinder.setRotationPoint(2F, 9.7F, -4F);
    Cilinder.setTextureSize(128, 64);
    Cilinder.mirror = true;
    setRotation(Cilinder, 0.3949506F, 0F, 0F);
    Cilinder = new ModelRenderer(this, 76, 24);
    Cilinder.addBox(0F, 0F, 0F, 2, 3, 2);
    Cilinder.setRotationPoint(-1F, 9.7F, -4F);
    Cilinder.setTextureSize(128, 64);
    Cilinder.mirror = true;
    setRotation(Cilinder, 0.3949506F, 0F, 0F);
    Cilinder = new ModelRenderer(this, 76, 24);
    Cilinder.addBox(0F, 0F, 0F, 2, 3, 2);
    Cilinder.setRotationPoint(-4F, 9.7F, -4F);
    Cilinder.setTextureSize(128, 64);
    Cilinder.mirror = true;
    setRotation(Cilinder, 0.3949506F, 0F, 0F);*/
  }

  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Shape1.render(f5);
   /* Shape2.render(f5);
    Shape3.render(f5);
    Shape4.render(f5);
    Shape4.render(f5);
    Shape5.render(f5);
    Shape5.render(f5);
    Shape2.render(f5);
    Shape2.render(f5);
    Shape2.render(f5);
    Shape6.render(f5);
    Shape6.render(f5);
    Shape6.render(f5);
    Shape6.render(f5);
    Shape7.render(f5);
    Shape8.render(f5);
    Shape8.render(f5);
    Cilinder.render(f5);
    Cilinder.render(f5);
    Cilinder.render(f5);
    Cilinder.render(f5);
    Cilinder.render(f5);
    Cilinder.render(f5);*/
  }

  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }
}