// Date: 21/07/2015 23:29:46
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelQuarry extends ModelBase
{
  //fields
    ModelRenderer QuarryBase;
    ModelRenderer 1;
    ModelRenderer 2;
    ModelRenderer 3;
    ModelRenderer 4;
    ModelRenderer 5;
    ModelRenderer 6;
    ModelRenderer 7;
    ModelRenderer 8;
    ModelRenderer 9;
    ModelRenderer 10;
    ModelRenderer 11;
    ModelRenderer 12;
    ModelRenderer 13;
    ModelRenderer 14;
    ModelRenderer 15;
    ModelRenderer 16;
    ModelRenderer 17;
    ModelRenderer 18;
  
  public ModelQuarry()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      QuarryBase = new ModelRenderer(this, 0, 0);
      QuarryBase.addBox(0F, 0F, 0F, 16, 15, 16);
      QuarryBase.setRotationPoint(-8F, 9F, -8F);
      QuarryBase.setTextureSize(128, 64);
      QuarryBase.mirror = true;
      setRotation(QuarryBase, 0F, 0F, 0F);
      1 = new ModelRenderer(this, 64, 0);
      1.addBox(0F, 0F, 6F, 1, 1, 2);
      1.setRotationPoint(-7F, 8F, -13F);
      1.setTextureSize(128, 64);
      1.mirror = true;
      setRotation(1, 0F, 0F, 0F);
      2 = new ModelRenderer(this, 64, 10);
      2.addBox(0F, 0F, 0F, 1, 1, 3);
      2.setRotationPoint(-6F, 8F, -7F);
      2.setTextureSize(128, 64);
      2.mirror = true;
      setRotation(2, 0F, 0F, 0F);
      3 = new ModelRenderer(this, 64, 14);
      3.addBox(0F, 0F, 0F, 1, 1, 3);
      3.setRotationPoint(-5F, 8F, -6F);
      3.setTextureSize(128, 64);
      3.mirror = true;
      setRotation(3, 0F, 0F, 0F);
      4 = new ModelRenderer(this, 64, 18);
      4.addBox(0F, 0F, 0F, 1, 1, 3);
      4.setRotationPoint(-4F, 8F, -5F);
      4.setTextureSize(128, 64);
      4.mirror = true;
      setRotation(4, 0F, 0F, 0F);
      5 = new ModelRenderer(this, 64, 22);
      5.addBox(0F, 0F, 0F, 1, 1, 3);
      5.setRotationPoint(-3F, 8F, -4F);
      5.setTextureSize(128, 64);
      5.mirror = true;
      setRotation(5, 0F, 0F, 0F);
      6 = new ModelRenderer(this, 64, 26);
      6.addBox(0F, 0F, 0F, 1, 1, 3);
      6.setRotationPoint(-2F, 8F, -3F);
      6.setTextureSize(128, 64);
      6.mirror = true;
      setRotation(6, 0F, 0F, 0F);
      7 = new ModelRenderer(this, 64, 30);
      7.addBox(0F, 0F, 0F, 1, 1, 3);
      7.setRotationPoint(-1F, 8F, -2F);
      7.setTextureSize(128, 64);
      7.mirror = true;
      setRotation(7, 0F, 0F, 0F);
      8 = new ModelRenderer(this, 64, 34);
      8.addBox(0F, 0F, 0F, 1, 1, 3);
      8.setRotationPoint(0F, 8F, -1F);
      8.setTextureSize(128, 64);
      8.mirror = true;
      setRotation(8, 0F, 0F, 0F);
      9 = new ModelRenderer(this, 64, 38);
      9.addBox(0F, 0F, 0F, 1, 1, 3);
      9.setRotationPoint(1F, 8F, 0F);
      9.setTextureSize(128, 64);
      9.mirror = true;
      setRotation(9, 0F, 0F, 0F);
      10 = new ModelRenderer(this, 64, 42);
      10.addBox(0F, 0F, 0F, 1, 1, 2);
      10.setRotationPoint(2F, 8F, 1F);
      10.setTextureSize(128, 64);
      10.mirror = true;
      setRotation(10, 0F, 0F, 0F);
      11 = new ModelRenderer(this, 64, 47);
      11.addBox(0F, 0F, 0F, 1, 1, 1);
      11.setRotationPoint(3F, 8F, 3F);
      11.setTextureSize(128, 64);
      11.mirror = true;
      setRotation(11, 0F, 0F, 0F);
      12 = new ModelRenderer(this, 64, 49);
      12.addBox(0F, 0F, 0F, 1, 1, 1);
      12.setRotationPoint(4F, 8F, 4F);
      12.setTextureSize(128, 64);
      12.mirror = true;
      setRotation(12, 0F, 0F, 0F);
      13 = new ModelRenderer(this, 76, 5);
      13.addBox(0F, 0F, 0F, 1, 1, 8);
      13.setRotationPoint(4F, 8F, -4F);
      13.setTextureSize(128, 64);
      13.mirror = true;
      setRotation(13, 0F, 0F, 0F);
      14 = new ModelRenderer(this, 75, 2);
      14.addBox(0F, 0F, 0F, 8, 1, 1);
      14.setRotationPoint(-4F, 8F, 4F);
      14.setTextureSize(128, 64);
      14.mirror = true;
      setRotation(14, 0F, 0F, 0F);
      15 = new ModelRenderer(this, 4, 33);
      15.addBox(0F, 0F, 0F, 1, 1, 5);
      15.setRotationPoint(5F, 8F, -3F);
      15.setTextureSize(128, 64);
      15.mirror = true;
      setRotation(15, 0F, 0F, 0F);
      16 = new ModelRenderer(this, 4, 41);
      16.addBox(0F, 0F, 0F, 5, 1, 1);
      16.setRotationPoint(-3F, 8F, 5F);
      16.setTextureSize(128, 64);
      16.mirror = true;
      setRotation(16, 0F, 0F, 0F);
      17 = new ModelRenderer(this, 2, 45);
      17.addBox(0F, 0F, 0F, 1, 1, 6);
      17.setRotationPoint(3F, 8F, -3F);
      17.setTextureSize(128, 64);
      17.mirror = true;
      setRotation(17, 0F, 0F, 0F);
      18 = new ModelRenderer(this, 19, 33);
      18.addBox(0F, 0F, 0F, 5, 1, 1);
      18.setRotationPoint(-2F, 8F, 3F);
      18.setTextureSize(128, 64);
      18.mirror = true;
      setRotation(18, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    QuarryBase.render(f5);
    1.render(f5);
    2.render(f5);
    3.render(f5);
    4.render(f5);
    5.render(f5);
    6.render(f5);
    7.render(f5);
    8.render(f5);
    9.render(f5);
    10.render(f5);
    11.render(f5);
    12.render(f5);
    13.render(f5);
    14.render(f5);
    15.render(f5);
    16.render(f5);
    17.render(f5);
    18.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
